package com.fzu.bean;

import java.util.Date;

public class course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_number
     *
     * @mbggenerated
     */
    private String courseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacId
     *
     * @mbggenerated
     */
    private Integer teacid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_time
     *
     * @mbggenerated
     */
    private Date classTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_location
     *
     * @mbggenerated
     */
    private String classLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_number
     *
     * @return the value of course.course_number
     *
     * @mbggenerated
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_number
     *
     * @param courseNumber the value for course.course_number
     *
     * @mbggenerated
     */
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber == null ? null : courseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacId
     *
     * @return the value of course.teacId
     *
     * @mbggenerated
     */
    public Integer getTeacid() {
        return teacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacId
     *
     * @param teacid the value for course.teacId
     *
     * @mbggenerated
     */
    public void setTeacid(Integer teacid) {
        this.teacid = teacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_time
     *
     * @return the value of course.class_time
     *
     * @mbggenerated
     */
    public Date getClassTime() {
        return classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_time
     *
     * @param classTime the value for course.class_time
     *
     * @mbggenerated
     */
    public void setClassTime(Date classTime) {
        this.classTime = classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_location
     *
     * @return the value of course.class_location
     *
     * @mbggenerated
     */
    public String getClassLocation() {
        return classLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_location
     *
     * @param classLocation the value for course.class_location
     *
     * @mbggenerated
     */
    public void setClassLocation(String classLocation) {
        this.classLocation = classLocation == null ? null : classLocation.trim();
    }
}